#!/bin/sh
#
# minis-install.sh — cross-platform installer for the paper-fetch CLI skill.
#
# Designed to "just work" across the environments where Minis (or any other
# host shell) runs, by detecting the platform and using the smoothest path.
#
# Two installation profiles are detected automatically:
#
#   * Minis / iSH / iOS  → Minis profile. ableSci uses the in-app WebView
#     driver (`minis-browser-use`) instead of Chrome cookies / OpenCLI, which
#     cannot work in the iSH sandbox (no DBUS, no access to the iOS Chrome
#     cookie store, Aliyun WAF blocks plain HTTP clients). Dependencies are
#     installed from Alpine packages + a --system-site-packages venv.
#
#   * Normal macOS / glibc Linux → classic profile.
#       - with uv  → official `uv tool install` (wheels cached, one line)
#       - no uv    → venv + pip (wheels exist)
#       ableSci uses Chrome cookies (browser-cookie3) with the OpenCLI
#       fallback, exactly as before.
#
# The installer also writes a `paper-fetch` wrapper into the skill dir that
# activates the venv, so `paper-fetch ...` works regardless of how the venv
# was created or whether its bin is on PATH.
#
# Usage (run from anywhere):
#   sh /path/to/paper-fetch/scripts/minis-install.sh
#   sh scripts/minis-install.sh          # from inside the skill dir
#
set -u

SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WRAPPER="$SKILL_DIR/paper-fetch"
VENV_DIR="$SKILL_DIR/venv"
UPSTREAM="git+https://github.com/CaseyTso/paper-fetch.git"

LOG(){ printf '%s\n' "$*"; }

need_py(){
  if ! command -v python3 >/dev/null 2>&1; then
    LOG "ERROR: python3 not found. Install Python 3.11+ and re-run this script."
    exit 1
  fi
  V=$("${PY:-python3}" -c 'import sys;print(f"{sys.version_info[0]}.{sys.version_info[1]}")' 2>/dev/null)
  LOG "    python3 = $V"
  # numeric check: major must be 3, minor must be >= 11
  MAJ=$("${PY:-python3}" -c 'import sys;print(sys.version_info[0])')
  MIN=$("${PY:-python3}" -c 'import sys;print(sys.version_info[1])')
  if [ "$MAJ" -lt 3 ] || { [ "$MAJ" -eq 3 ] && [ "$MIN" -lt 11 ]; }; then
    LOG "ERROR: paper-fetch needs Python >= 3.11 (found ${MAJ}.${MIN})."
    exit 1
  fi
}

detect(){
  MUSL=0
  if command -v ldd >/dev/null 2>&1 && ldd --version 2>&1 | grep -qi musl; then
    MUSL=1
  elif [ -e /etc/alpine-release ] || [ -n "${ISH_TMPDIR:-}" ] || \
       grep -qi alpine /etc/os-release 2>/dev/null; then
    MUSL=1
  fi
  # Minis profile: /var/minis exists AND the in-app browser CLI is present.
  # This is what unlocks the ableSci WebView driver (see SKILL.md).
  MINIS=0
  if [ -d /var/minis ] && command -v minis-browser-use >/dev/null 2>&1; then
    MINIS=1
  fi
  need_py
}

install_musl(){
  LOG "==> Detected musl/Alpine-like environment (iSH etc.) — using prebuilt lz4"
  if ! command -v apk >/dev/null 2>&1; then
    LOG "ERROR: no 'apk' found. Install the system python-lz4 package, e.g."
    LOG "       apk add py3-lz4 py3-lz4-pyc" 
    exit 1
  fi
  apk add --no-cache py3-lz4 py3-lz4-pyc || {
    LOG "NOTE: 'apk add' failed. Run as root:  apk add py3-lz4 py3-lz4-pyc"
    exit 1
  }
  LOG "==> Creating venv with system-site-packages (lets it see Alpine's lz4)"
  if ! python3 -m venv --system-site-packages "$VENV_DIR" 2>&1; then
    LOG "ERROR: could not create a venv at $VENV_DIR."
    LOG "       This usually means the directory is on a filesystem without"
    LOG "       symlink support (e.g. some app-synced/iCloud-like mounts)."
    LOG "       Install the skill under a normal location (e.g. /var/minis/skills/)"
    LOG "       and re-run this script."
    exit 1
  fi
  "$VENV_DIR/bin/pip" install --upgrade pip >/dev/null 2>&1 || true
  LOG "==> Installing deps + package into venv"
  # Plain editable install: pip satisfies lz4 from the system site-packages,
  # and pycryptodomex/others resolve to musllinux wheels (or pure wheels).
  "$VENV_DIR/bin/pip" install -e "$SKILL_DIR" 2>&1 | tail -6 \
    || { LOG "editable install failed; printing diagnostic below"; "$VENV_DIR/bin/pip" install -e "$SKILL_DIR" -v 2>&1 | tail -20; exit 1; }
}

install_uv(){
  if command -v uv >/dev/null 2>&1; then
    LOG "==> Installing via uv (official path)"
    uv tool install "$UPSTREAM" 2>&1 | tail -4
    return 0
  fi
  install_venv_pip
}

install_venv_pip(){
  LOG "==> venv + pip (no uv present; wheels are available on this platform)"
  python3 -m venv "$VENV_DIR" || { LOG "venv failed"; exit 1; }
  "$VENV_DIR/bin/pip" install --upgrade pip >/dev/null 2>&1 || true
  "$VENV_DIR/bin/pip" install -e "$SKILL_DIR" 2>&1 | tail -6
}

make_wrapper(){
  # Local wrapper that activates the venv and dispatches to its paper-fetch.
  # Needed for the musl / venv-pip paths (and harmless when uv put the binary
  # on PATH). Only written under /var/minis so we never litter a fresh clone.
  case "$SKILL_DIR" in
    /var/minis/*) ;;
    *) return 0 ;;
  esac
  cat > "$WRAPPER" <<EOF
#!/bin/sh
# Auto-generated by scripts/minis-install.sh — do not edit.
. "$VENV_DIR/bin/activate"
exec paper-fetch "\$@"
EOF
  chmod +x "$WRAPPER"
}

# ----- main ---------------------------------------------------------------
detect

if [ "$MINIS" = "1" ]; then
  LOG ""
  LOG "==> Minis profile detected (in-app browser available)"
  LOG "    ableSci will use the Minis WebView driver (minis-browser-use);"
  LOG "    Chrome cookies / OpenCLI are NOT required in this environment."
  LOG ""
fi

if [ "$MUSL" = "1" ]; then
  install_musl
else
  install_uv
fi

make_wrapper

# Sanity check
if [ -x "$VENV_DIR/bin/paper-fetch" ] || [ -x "$WRAPPER" ] || command -v paper-fetch >/dev/null 2>&1; then
  LOG ""
  LOG "==> paper-fetch installed OK."
  LOG "    • code:      $SKILL_DIR"
  LOG "    • venv:      $VENV_DIR"
  if [ "$MINIS" = "1" ]; then
    LOG "    • ableSci:   Minis WebView driver (minis-browser-use)"
    LOG "      For ableSci, log in once inside the Minis in-app browser at"
    LOG "      https://www.ablesci.com — the session persists across runs."
  else
    LOG "    • ableSci:   Chrome cookies (browser-cookie3) + OpenCLI fallback"
    LOG "      For ableSci, log in once in Google Chrome (see references/ablesci-login.md)."
  fi
  if [ -x "$WRAPPER" ]; then
    LOG "    • wrapper:   $WRAPPER   (use this on PATH)"
    LOG "    Health-check:  $WRAPPER doctor --json"
  else
    LOG "    • binary:    $VENV_DIR/bin/paper-fetch   (add its dir to PATH, or use the full path)"
    LOG "    Health-check:  $VENV_DIR/bin/paper-fetch doctor --json"
  fi
else
  LOG "==> Install did not fully complete. Review the messages above."
  exit 1
fi
